name: Check Release Assets
on:
  release:
    types:
       - published
env:
  DIST_NAME: test_gha
jobs:
  Assets:
    runs-on: ubuntu-latest
    env:
      DIST_FILE: ${{ vars.DIST_NAME }}-${{ github.event.release.tag_name }}.tar.gz
    steps:
      - name: Fetch Assets
        uses: cb80/dlassets@latest
        with:
          tag: ${{ github.event.release.tag_name }}
          to: dist
      - name: Check Dist Dir
        run: |
          ls -la dist
      - name: Check _meta
        run: |
          tar --extract --file dist/$DIST_FILE --gzip --to-stdout ${DIST_FILE%%.tar.gz}/_meta.py
