name: Check Release Assets
on:
  release:
    types:
       - published
jobs:
  Assets:
    runs-on: ubuntu-latest
    env:
      SDIST: test_gha-${{ github.event.release.tag_name }}.tar.gz
    steps:
      - name: Fetch Assets
        uses: cb80/dlassets@latest
        with:
          tag: ${{ github.event.release.tag_name }}
          to: dist
      - name: Check Dist Dir
        run: |
          ls -la dist
      - name: Check _meta
        run: |
          tar --extract --file dist/$SDIST --gzip --to-stdout ${SDIST%%.tar.gz}/_meta.py
